view:
  site:
    wxPayEnable: ${wx.pay.enable}
    needLoginArticleReadCount: 30 # 需要登录才能阅读的文章阅读次数
    zsxqArticleReadCount: 20 # 知识星球用户才能阅读的文章阅读次数统计间隔，单位：分钟
    needPayArticleReadCount: 20 # 付费文章，未付费可以看到的文章内容
    websiteName: 极客航路
    websiteLogoUrl: https://geek-route.asia/img/logo.svg
    websiteFaviconIconUrl: https://geek-route.asia/img/icon.png
    zsxqUrl:
    zsxqPosterUrl:
    contactMeTitle: 联系我 - 程序员曼布
    contactMeWxQrCode:
    contactMeStarQrCode:
    pageSize: 20
    cdnImgStyle:
    websiteRecord: 备案被小人偷袭了
    wxLoginUrl:
    host: http://127.0.0.1:${server.port}
    welcomeInfo: 欢迎来到极客航路，戳<a href="/article/detail/15">极客航路全方位视角解读</a>了解我们
    oss: