spring:
  mail:
    host: smtp.qq.com
    port: 465
    username: 2530986792@qq.com     # 如 12345678@qq.com
    password: aqvlrgeuhhhddjfd            # 注意：不是邮箱密码，是授权码！
    from: 2530986792@qq.com
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
            fallback: false
          starttls:
            enable: true
            required: true

alarm:
  user: 2530986792@qq.com
