image:
  # 服务器保存图片的绝对地址
  abs-tmp-path: /home/admin/storage/
  # 图片前缀
  web-img-path: forum/img/
  # 临时存储目录
  tmp-upload-path: /tmp/forum/
  # 图片访问域名
  cdn-host: https://www.geek-route.asia/
  oss:
    type: local
    endpoint: oss-cn-beijing.aliyuncs.com
    prefix: image/
    ak: LTAI5t7epaeGRvcEPJssQ2ZE
    sk:
    bucket: web-c-q-waimai
    host: https://web-c-q-waimai.oss-cn-beijing.aliyuncs.com/