view:
  site:
    wxPayEnable: ${wx.pay.enable}
    needLoginArticleReadCount: 30 # 需要登录才能阅读的文章阅读次数
    zsxqArticleReadCount: 20 # 知识星球用户才能阅读的文章阅读次数统计间隔，单位：分钟
    needPayArticleReadCount: 20 # 付费文章，未付费可以看到的文章内容
    websiteName: 极客航路
    websiteLogoUrl: https://www.geek-route.asia/img/logo.svg
    websiteFaviconIconUrl: https://www.geek-route.asia/img/icon.png
    contactMeTitle: 联系我 - 程序员曼布
    contactMeWxQrCode: https://web-c-q-waimai.oss-cn-beijing.aliyuncs.com/qrcode_for_gh_57e2daae5c4e_258%20%281%29.jpg
    pageSize: 20
    cdnImgStyle:
    websiteRecord: 备案被小人偷袭了
    wxLoginUrl: https://web-c-q-waimai.oss-cn-beijing.aliyuncs.com/qrcode_for_gh_57e2daae5c4e_258%20%281%29.jpg
    host: https://www.geek-route.asia
    welcomeInfo: 欢迎来到极客航路，戳 <a href="/article/detail/155">极客航路社区上线！</a> 了解我们
    zsxqUrl:
    zsxqPosterUrl:
    contactMeStarQrCode: https://web-c-q-waimai.oss-cn-beijing.aliyuncs.com/qrcode_for_gh_57e2daae5c4e_258%20%281%29.jpg
    oss: https://www.geek-route.asia/

knife4j:
  production: true # 开启屏蔽文档资源